---
title: "Critical abundance paper"
output: html_notebook
---

Analyses of the critical abundances for the impact of non-native plants on native grassland plant communities of Banks peninsula.

```{r setup, echo=FALSE}

setwd("/Users/maud/Documents/Work/Postdoc lincoln local /R/R_critical abundances analyses")

# load packages
library(doBy)
library(vegan)
library(markdown)
require(rgdal)
require(rgeos)
require(raster)
require(sp)
require(maps)
library(raster)
library(prettymapr)

# load("saved Rdata/article 2 - threshold/article threshold 1.3.4.Rdata") 

```


```{r data import, echo=FALSE, error=TRUE, results='hide', tidy=TRUE}
### Import and modify data from scratch:  ############
source('scripts/data/import BP species and environment data.R', encoding = "native.enc")
# source('script/data/import trait data.R', encoding = "native.enc")

# import GIS data
source('scripts/data/import GIS data.R', echo=FALSE)

# update envplot
source('~/Documents/Work/Postdoc lincoln local /R/R_critical abundances analyses/scripts/article 2 - Thresholds/modify envplot.R')

```

We selected `r length(unimprovedgrasslands)` plots of unimproved grasslands.

```{r map, echo = FALSE}

# Map of land use and selected plots
par(mar=c(0,0,2,2))
plot(region, col = "grey50", border = NA)
polygon(extent(region)[c(1,2,2,1)], extent(region)[c(3,3,4,4)], col ="lightblue", border = NA)
plot(region, add= T, col = "grey70", border = NA)
plot(study_area, add= T, col = "grey90", border = NA)
plot(envplot[envplot$PLOTID %in% unimprovedgrasslands,], add= T,  col ="goldenrod",bg ="goldenrod", pch = 22, cex = 0.7)
```


