---
title: "Gamma trends"
author: "Maudbv"
date: "6 August 2015"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gamma, beta and alpha trends





```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

#########    plot GAMMA diversity  ##########
par(mfrow = c(4,3), mar=c(4,4,1,1))
for (i in 1 : length(impsp)){

plot(c(1,6.3),range(gamma.trend.nat$obs[i,],gamma.trend.nat.permute$q975[i,]), type = "n", ann=F, las = 1)
segments(1:6,t(gamma.trend.nat$q025[i,]),
         1:6,t(gamma.trend.nat$q975[i,]), col="grey", lwd = 3)

segments(1.1:6.1,t(gamma.trend.nat.below$q025[i,]),
         1.1:6.1,t(gamma.trend.nat.below$q975[i,]), col="palegreen", lwd = 3)
segments(1.2:6.2,t(gamma.trend.nat.below$q025[i,]),
         1.2:6.2,t(gamma.trend.nat.below$q975[i,]), col="goldenrod", lwd = 3)

points(1:6,gamma.trend.nat$mean[i,],pch= 20, col="darkgrey")
points(1:6,gamma.trend.nat$obs[i,])
mtext(3, text = sub("_", " ",species[impsp[i],"tip"]), cex = 0.8)
}

plot(1:10,1:10,type = "n", ann=F,axes=F)
legend('left', legend = c("observed", "permute with rare occurrences", 
                            "permute with lower abundances","permute with all plots"),
       lty=c(NA, rep("solid",3)), lwd=c(0,5,5,5), pch=c(21, NA, NA, NA),
             col=c("black", "grey", "palegreen", "goldenrod"), bty= "n",
       cex = 0.8)

## plot Standardized effect sizes
x11()
par(mfrow = c(4,3), mar=c(4,4,1,1))
for (i in 1 : length(impsp)){
cols <- c(NA, "black") [ (gamma.trend.nat$P.gamma[i,] <=0.025) +1]
x = 1:6
y =(gamma.trend.nat$obs[i,] - gamma.trend.nat$mean[i,])/ gamma.trend.nat$sd[i,]
y[1]=0
plot(x,y,ylim= c(-5,4),xlim= c(1,6.3),ann=F, las = 1, pch = 21, col ="black",bg = cols, type= "b")


cols <- c(NA, "forestgreen") [ (gamma.trend.nat.below$P.gamma[i,] <=0.025) +1]
x = 1.1:6.1
y =(gamma.trend.nat.below$obs[i,] - gamma.trend.nat.below$mean[i,])/ gamma.trend.nat.below$sd[i,]
par(new=T)
plot(x,y,ylim= c(-5,4),xlim= c(1,6.3),pch = 21, col ="forestgreen",bg = cols, type= "b",ann=F, axes=F)

cols <- c(NA, "goldenrod") [ (gamma.trend.nat.permute$P.gamma[i,] <=0.025) +1]
x = 1.2:6.2
y =(gamma.trend.nat.permute$obs[i,] - gamma.trend.nat.permute$mean[i,])/ gamma.trend.nat.permute$sd[i,]
par(new=T)
plot(x,y,ylim= c(-5,4),xlim= c(1,6.3),pch = 21, col ="goldenrod",bg = cols, type= "b",ann=F, axes = F)

abline(h=0, lty="dotted", col="darkgrey")
mtext(3, text = impsp[i], cex = 0.8)
}
plot(1:10,1:10,type = "n", ann=F,axes=F)
legend('left', legend = c("permute with rare occurrences", 
                          "permute with lower abundances","permute with all plots"),
       lty=rep("solid",3),  pch=c(21, 21, 21),
       col=c("black", "palegreen", "goldenrod"),
       bty= "n",cex = 0.8)
# 
# 
# ########### plot BETA diversity #############
# 
# 
# x11()
# par(mfrow = c(4,3), mar=c(4,4,1,1))
# for (i in 1 : length(impsp)){
#   
#   plot(c(1,6.3),range(beta.trend.nat$obs[i,],beta.trend.nat.permute$q975[i,], na.rm = T), type = "n", ann=F, las = 1)
#   segments(1:6,t(beta.trend.nat$q025[i,]),
#            1:6,t(beta.trend.nat$q975[i,]), col="grey", lwd = 3)
#   
#   segments(1.1:6.1,t(beta.trend.nat.below$q025[i,]),
#            1.1:6.1,t(beta.trend.nat.below$q975[i,]), col="palegreen", lwd = 3)
#   segments(1.2:6.2,t(beta.trend.nat.below$q025[i,]),
#            1.2:6.2,t(beta.trend.nat.below$q975[i,]), col="goldenrod", lwd = 3)
#   
#   points(1:6,beta.trend.nat$mean[i,],pch= 20, col="darkgrey")
#   points(1:6,beta.trend.nat$obs[i,])
#   mtext(3, text = sub("_", " ",species[impsp[i],"tip"]), cex = 0.8)
# }
# 
# plot(1:10,1:10,type = "n", ann=F,axes=F)
# legend('left', legend = c("observed", "permute with rare occurrences", 
#                           "permute with lower abundances","permute with all plots"),
#        lty=c(NA, rep("solid",3)), lwd=c(0,5,5,5), pch=c(21, NA, NA, NA),
#        col=c("black", "grey", "palegreen", "goldenrod"), bty= "n",
#        cex = 0.8)
# 
# ## plot Standardized effect sizes
# x11()
# par(mfrow = c(4,3), mar=c(4,4,1,1))
# for (i in 1 : length(impsp)){
#   cols <- c(NA, "black") [ (beta.trend.nat$P.beta[i,] <=0.025) +1]
#   x = 1:6
#   y =(beta.trend.nat$obs[i,] - beta.trend.nat$mean[i,])/ beta.trend.nat$sd[i,]
#   y[1]=0
#   plot(x,y,ylim= c(-5,4),xlim= c(1,6.3),ann=F, las = 1, pch = 21, col ="black",bg = cols, type= "b")
#   
#   cols <- c(NA, "forestgreen") [ (beta.trend.nat.below$P.beta[i,] <=0.025) +1]
#   x = 1.1:6.1
#   y =(beta.trend.nat.below$obs[i,] - beta.trend.nat.below$mean[i,])/ beta.trend.nat.below$sd[i,]
#   par(new=T)
#   plot(x,y,ylim= c(-5,4),xlim= c(1,6.3),pch = 21, col ="forestgreen",bg = cols, type= "b",ann=F, axes=F)
#   
#   cols <- c(NA, "goldenrod") [ (beta.trend.nat.permute$P.beta[i,] <=0.025) +1]
#   x = 1.2:6.2
#   y =(beta.trend.nat.permute$obs[i,] - beta.trend.nat.permute$mean[i,])/ beta.trend.nat.permute$sd[i,]
#   par(new=T)
#   plot(x,y,ylim= c(-5,4),xlim= c(1,6.3),pch = 21, col ="goldenrod",bg = cols, type= "b",ann=F, axes = F)
#   
#   abline(h=0, lty="dotted", col="darkgrey")
#   mtext(3, text = impsp[i], cex = 0.8)
# }
# 
# plot(1:10,1:10,type = "n", ann=F,axes=F)
# legend('left', legend = c("permute with rare occurrences", 
#                           "permute with lower abundances","permute with all plots"),
#        lty=rep("solid",3),  pch=c(21, 21, 21),
#        col=c("black", "palegreen", "goldenrod"),
#        bty= "n",cex = 0.8)


spnames = rownames(glmSRnat.overall$mean)
par(mfrow = c(8,10), mar=c(0,0,2,1), oma=c(3,3,2,1))
ylim=c(-5,4)
for (i in 1 : length(spnames)){
  sp <- spnames[i]
  # identify significant classes in black
  cols <- c(NA, "black") [ ((gamma.trend.nat$P.gamma[i,] <=0.025) | (gamma.trend.nat$P.gamma[i,] >=0.975) ) +1]
  
  # create x axis for the 5 abundance classes
  x = c(0:5)
  
  # create y axis with the gamma richness Standardized effect size
  y =(gamma.trend.nat$obs[i,] - gamma.trend.nat$mean[i,])/ gamma.trend.nat$sd[i,]
  y[1]=NA
  
  # plot background
  plot(x,y,ylim=ylim, xlim = c(0.5, 5.5), las = 1,type= "p", xaxt = "n", yaxt="n", ann=F,
       pch = 21, col ="black",bg = cols)
  
  axis(1,at = 1:5, label = rep("",5), tcl= 0.1,mgp=c(1,0.5,0),las=1)
#   if (i %in% c(7:9)) text(y=-6, x = 1:5, labels= abclasses[2:6],  cex=0.8, srt=45, adj=1, xpd = NA)
  
#   if ( i %in% c(1,4,7)) axis(2, tcl= 0.1,  mgp=c(1,0.5,0), las=1)  
   abline(h=0,lty="dotted")
#   
  #plot points and lines
  par(new=T)
  plot(x,y, bg = cols, pch=21, type = "b",ylim=ylim, xlim = c(0.5, 5.5), xaxt = "n", yaxt="n", ann=F)
  
  # Add species name
  mtext(3, text=paste(species[sp, "Genus"], "\n",species[sp, "Species"], sep="") ,
        font = 3, outer= F,adj=0.9, cex=0.6, line=0, las = 1)
  
  # Y axis label
  if ( i %in% c(1,4,7)) {  
    mtext(2, text="SES", ,adj=0.5, cex=0.8, line=1.5, las = 0)
  }
}

mtext(1, text=c("Abundance class"), adj=0.5, line=2, las = 1, outer=T)
mtext(2, text=c("Variation in native gamma richness"), adj=0.5, line=2, las = 0, outer=T)



## betas
spnames = rownames(glmSRnat.overall$mean)
par(mfrow = c(8,10), mar=c(0,0,2,1), oma=c(3,3,2,1))
ylim=c(-5,4)
for (i in 1 : length(spnames)){
  sp <- spnames[i]
  # identify significant classes in black
  cols <- c(NA, "black") [ ((geta.trend.nat$P.beta[i,] <=0.025) | (beta.trend.nat$P.beta[i,] >=0.975) ) +1]
  
  # create x axis for the 5 abundance classes
  x = c(0:5)
  
  # create y axis with the gamma richness Standardized effect size
  y =(beta.trend.nat$obs[i,] - beta.trend.nat$mean[i,])/ beta.trend.nat$sd[i,]
  y[1]=NA
  
  # plot background
  plot(x,y,ylim=ylim, xlim = c(0.5, 5.5), las = 1,type= "p", xaxt = "n", yaxt="n", ann=F,
       pch = 21, col ="black",bg = cols)
  
  axis(1,at = 1:5, label = rep("",5), tcl= 0.1,mgp=c(1,0.5,0),las=1)
  #   if (i %in% c(7:9)) text(y=-6, x = 1:5, labels= abclasses[2:6],  cex=0.8, srt=45, adj=1, xpd = NA)
  
  #   if ( i %in% c(1,4,7)) axis(2, tcl= 0.1,  mgp=c(1,0.5,0), las=1)  
  abline(h=0,lty="dotted")
  #   
  #plot points and lines
  par(new=T)
  plot(x,y, bg = cols, pch=21, type = "b",ylim=ylim, xlim = c(0.5, 5.5), xaxt = "n", yaxt="n", ann=F)
  
  # Add species name
  mtext(3, text=paste(species[sp, "Genus"], "\n",species[sp, "Species"], sep="") ,
        font = 3, outer= F,adj=0.9, cex=0.6, line=0, las = 1)
  
  # Y axis label
  if ( i %in% c(1,4,7)) {  
    mtext(2, text="SES", ,adj=0.5, cex=0.8, line=1.5, las = 0)
  }
}

mtext(1, text=c("Abundance class"), adj=0.5, line=2, las = 1, outer=T)
mtext(2, text=c("Variation in native gamma richness"), adj=0.5, line=2, las = 0, outer=T)

```

